package idat.edu.pe.Entidad;
// Generated 24/11/2018 10:17:40 AM by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private String idCurso;
     private String nomCurso;
     private Integer credito;

    public Curso() {
    }

	
    public Curso(String idCurso, String nomCurso) {
        this.idCurso = idCurso;
        this.nomCurso = nomCurso;
    }
    public Curso(String idCurso, String nomCurso, Integer credito) {
       this.idCurso = idCurso;
       this.nomCurso = nomCurso;
       this.credito = credito;
    }
   
    public String getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(String idCurso) {
        this.idCurso = idCurso;
    }
    public String getNomCurso() {
        return this.nomCurso;
    }
    
    public void setNomCurso(String nomCurso) {
        this.nomCurso = nomCurso;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }




}


