package idat.edu.pe.Entidad;
// Generated 24/11/2018 10:17:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Especialidad generated by hbm2java
 */
public class Especialidad  implements java.io.Serializable {


     private String idesp;
     private String nomesp;
     private BigDecimal costo;

    public Especialidad() {
    }

    public Especialidad(String idesp, String nomesp, BigDecimal costo) {
       this.idesp = idesp;
       this.nomesp = nomesp;
       this.costo = costo;
    }
   
    public String getIdesp() {
        return this.idesp;
    }
    
    public void setIdesp(String idesp) {
        this.idesp = idesp;
    }
    public String getNomesp() {
        return this.nomesp;
    }
    
    public void setNomesp(String nomesp) {
        this.nomesp = nomesp;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }




}


