package idat.edu.pe.Entidad;
// Generated 24/11/2018 10:17:40 AM by Hibernate Tools 4.3.1



/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private NotasId id;
     private Float exaParcial;
     private Float exaFinal;

    public Notas() {
    }

	
    public Notas(NotasId id) {
        this.id = id;
    }
    public Notas(NotasId id, Float exaParcial, Float exaFinal) {
       this.id = id;
       this.exaParcial = exaParcial;
       this.exaFinal = exaFinal;
    }
   
    public NotasId getId() {
        return this.id;
    }
    
    public void setId(NotasId id) {
        this.id = id;
    }
    public Float getExaParcial() {
        return this.exaParcial;
    }
    
    public void setExaParcial(Float exaParcial) {
        this.exaParcial = exaParcial;
    }
    public Float getExaFinal() {
        return this.exaFinal;
    }
    
    public void setExaFinal(Float exaFinal) {
        this.exaFinal = exaFinal;
    }




}


