package idat.edu.pe.Entidad;
// Generated 24/11/2018 10:17:40 AM by Hibernate Tools 4.3.1



/**
 * NotasId generated by hbm2java
 */
public class NotasId  implements java.io.Serializable {


     private String idAlumno;
     private String idCurso;

    public NotasId() {
    }

    public NotasId(String idAlumno, String idCurso) {
       this.idAlumno = idAlumno;
       this.idCurso = idCurso;
    }
   
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(String idCurso) {
        this.idCurso = idCurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotasId) ) return false;
		 NotasId castOther = ( NotasId ) other; 
         
		 return ( (this.getIdAlumno()==castOther.getIdAlumno()) || ( this.getIdAlumno()!=null && castOther.getIdAlumno()!=null && this.getIdAlumno().equals(castOther.getIdAlumno()) ) )
 && ( (this.getIdCurso()==castOther.getIdCurso()) || ( this.getIdCurso()!=null && castOther.getIdCurso()!=null && this.getIdCurso().equals(castOther.getIdCurso()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode() );
         result = 37 * result + ( getIdCurso() == null ? 0 : this.getIdCurso().hashCode() );
         return result;
   }   


}


