package idat.edu.pe.Entidad;
// Generated 24/11/2018 10:17:40 AM by Hibernate Tools 4.3.1



/**
 * PagosId generated by hbm2java
 */
public class PagosId  implements java.io.Serializable {


     private String idAlumno;
     private String ciclo;
     private int ncuota;

    public PagosId() {
    }

    public PagosId(String idAlumno, String ciclo, int ncuota) {
       this.idAlumno = idAlumno;
       this.ciclo = ciclo;
       this.ncuota = ncuota;
    }
   
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(String ciclo) {
        this.ciclo = ciclo;
    }
    public int getNcuota() {
        return this.ncuota;
    }
    
    public void setNcuota(int ncuota) {
        this.ncuota = ncuota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagosId) ) return false;
		 PagosId castOther = ( PagosId ) other; 
         
		 return ( (this.getIdAlumno()==castOther.getIdAlumno()) || ( this.getIdAlumno()!=null && castOther.getIdAlumno()!=null && this.getIdAlumno().equals(castOther.getIdAlumno()) ) )
 && ( (this.getCiclo()==castOther.getCiclo()) || ( this.getCiclo()!=null && castOther.getCiclo()!=null && this.getCiclo().equals(castOther.getCiclo()) ) )
 && (this.getNcuota()==castOther.getNcuota());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode() );
         result = 37 * result + ( getCiclo() == null ? 0 : this.getCiclo().hashCode() );
         result = 37 * result + this.getNcuota();
         return result;
   }   


}


